language: android
sudo: required
jdk: oraclejdk8

env:
 global:
 - ANDROID_API=26
 - EMULATOR_API=23
 - ANDROID_BUILD_TOOLS=26.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
 components:
 - tools
 - platform-tools
 - extra
 - build-tools-26.0.2
 - android-26

before_install:
  - chmod +x gradlew
  - ./gradlew dependencies || true

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build
  - ./gradlew testDebugUnitTest --stacktrace
  - ./gradlew connectedDebugAndroidTest --stacktrace